lisk-builders/lisk-builders

- data/delegates.json
Hi Lisk.builders 👋 ,
I’ve prepared my PR to get into the lisk.builders project.
About me, I’m a passionate Full Stack JS developer living in Berlin. Coding enables me to create the tools that I need and things that I can imagine. Recently I’ve created a crypto asset tracker that follows the major cryptocurrency wallets (of course lisk is included), helps traders with some handy trading tools,  including trading functionalities with exchanges such as dynamic stop limits and market emotions backed by AI (this feature is currently not stable and I’m still studying the results). At the moment the bot is in private beta testing phase and will be released in the near future.
Furthermore I’m currently also developing a couple of tools for the Lisk ecosystem. I hope to announce my first tool next …
> Carbonara: My presentation for lisk.builders

- data/delegates.json
Thanks for ur work ! Hope we can discuss the way to become a Lottery Member !
> Delegate_update_by_LiskPro

- data/delegates.json
Because I'm _literally_ a builder. I would even consider applying to join the pool as full member in the long run once I am more actively contributing to the Lisk development. Let me know what you think.
> Add 4fryn to the list of builders.

- data/notes.json
- scripts/App.js
- scripts/Contributions.js
- scripts/NavBar.js
- scripts/index.js
> Add contributions page

- scripts/NavBar.js
> Use js to show/hide menu

- data/delegates.json
data shamelessly scraped from reddit
https://www.reddit.com/r/LiskDelegates/comments/7fpdtj/sherwood_advice_vote_for_all_members_to_get_your/
> Add lisk-pro sherwood affiliation.

- data/delegates.json
I already introduced myself in slack :)
I'm Tobi - 22 years old and from Austria! I love coding (Fullstack JS) and ofc lisk!
I already did some contributions to lisk-js and one small change for lisk-core!
I am currently working on some lisk projects in my spare time:
- Lisk Telegram Bot (@LiskToolBot) 
- Lisk Pending API (For the Bot)
- Lisk Mobile (in work)
- Lisk Delegate (elevate) (in work)
- Lisk Pool (new nodejs based pool; currently planning - want your Feedback if useful)
- Lisk.Supply (Brand of all products listed above) 
And planning to do much more
> add elevate to delegates

- data/delegates.json
I updated the reward spending as described in my proposals!
Also changed the affiliation to freelance -> else it would look like a group/pool
> change to freelance and update reward spending

- data/delegates.json
Hi Lisk.builders members :wave: ,
I am making a PR and I'm hoping to get accepted into the lisk.builders project as it would be great to be a part of this community.
About me, I'm a freelance PHP coder but often code using Javascript, NodeJS and Electron as well as a few other languages currently living in the UK. I like to make simple tools that are useful to the Lisk community and have also started to make Browser extensions but plan to make larger projects as well as Lisk Sidechains in the future. 
I will be updating my current projects and would also like to start coding Mobile and Tablet apps, I have just got an Amazon Alexa and was hoping to make a Skill for Lisk. I am also very interested in Artificial intelligence recently and will try to build it into a future project.
I found …
> BlueDragon: My presentation for lisk.builders

- data/delegates.json
As per https://forum.lisk.io/viewtopic.php?f=48&t=1560
> Update 4fryn poolPercentage

- data/delegates.json
Hello Builders!
I'm extremely excited to contribute and grow the Lisk platform and community as best I can. I currently Lead iOS development at Barstool Sports, previously lead mobile for Tablelist and interned at WhatsApp. I consider myself fluent in both Swift and JavaScript/Node.js, splitting my time almost equally between the two. My initial draw to Lisk was the fact it ran on Node.js but I fell in love with Lisk because of how approachable the codebase and developer tools are. As I began learning the Lisk API I saw a strong need for an SDK that could be used to develop iOS/macOS apps that communicate with the Lisk network. There are a handful of SDKs that simply wrap the HTTP API but nothing secure/sophisticated enough to actually sign and broadcast transactions to the network the …
> Add andrew to delegates.json

- data/groups.json
Add @AndrewBarba to builders group in /data
> Add andrew to builders group in /data

- data/delegates.json
#1. Hello Lisk Builders 😊
I finally decided to make this PR and join your community as your work and entire Lisk Project inspired me to go out of comfort zone and do something more. I already gained few new skills from variety areas, like creation of vector graphic, gif banners, node maintenance, basics of html/css/js website creation, social media advertising and probably couple more 😉
#2. About me?
I am an administrator of the Business Intelligence (Big Data etc.) platform for big client from USA. My background was Robotics and automatics, but many things pushed me to IT and I am glad I went that route. I live near Warsaw and working remotely from home. In day-job I need variety skills, like SQL, Unix knowledge and bash scripting, databases, JavaScript for some visualization and of …
> LiskPoland.pl proposal to join Lisk.Builders

- data/groups.json
> Data: Add hirish to LIG

- data/groups.json
> Data: Remove vipertkd from Ark Founding Team

- data/groups.json
- Ascend Pool Bonus is 50%
- Add lisktrust to Ascend
> Data: Update Ascend

- data/delegates.json
- data/groups.json
- scripts/votemanager/VoteManagerControls.tsx
- ascend: fix typo for gregorst
- ascend: add slamper, add puredelta
- sherwood: add bitbanksy, 4fryn, bloqspace
- builders: update sherwood affiliation for 4fryn
- builders: feature 4fryn, elevate, endro
- votemanager: adjust lists to fit 101
> Pool updates

- data/groups.json
- 4miners left GDT
- hirish joined GDT, left Ascend
> Data: update groups

- data/groups.json
> Data: bitbanksy left Sherwood

- data/delegates.json
- data/groups.json
I added myself to the list of Lisk Builders since I really like this team of active contributors 👍 
Most of you already know me from Lisk.chat and your Slack.
You can read more about my contributions [here](https://blog.lisk.io/lisk-community-member-spotlight-hendrik-aka-slamper-360912ba246)
> Data: Add slamper to builders group

- src/data/delegates.json
- src/data/groups.json
- src/data/pools.json
> Pool update Moosty
